version: '3.8'
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana-historical-treshold
    # restart: unless-stopped
    # if you are running as root then set it to 0
    # else find the right id with the id -u command
    user: '0'
    ports:
      - '3011:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      - .env
      - influxv2.env
    environment:
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}

    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning

  mongodb:
    image: prismagraphql/mongo-single-replica:5.0.3
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=thresholds
    volumes:
      - ./mongo-initdb/mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
      - ./mongo-initdb/db.dump:/db.dump
      - mongodb-storage:/data/db

      
  influxdb:
    image: influxdb:2.6-alpine
    container_name: influxdb-historical-treshold
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      - influxv2.env
    volumes:
      # Mount for influxdb data directory and configuration
      - influxdbv2-storage:/var/lib/influxdb2:rw
    ports:
      - "8087:8086"

  telegraf1:
    image: telegraf:1.25-alpine
    hostname: host1
    container_name: telegraf-host1
    depends_on:
      - influxdb
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      # Mount for telegraf config
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    env_file:
      - influxv2.env

  telegraf2:
    image: telegraf:1.25-alpine
    hostname: host2
    container_name: telegraf-host2
    depends_on:
      - influxdb
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      # Mount for telegraf config
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    env_file:
      - influxv2.env      

  telegraf3:
    image: telegraf:1.25-alpine
    hostname: host3
    container_name: telegraf-host3
    depends_on:
      - influxdb
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      # Mount for telegraf config
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    env_file:
      - influxv2.env

volumes:
  grafana-storage:
  influxdbv2-storage:
  mongodb-storage: